[General]
ScreenWidth="5120"
ScreenHeight="1440"
ScreenPadding=""

Font="JetBrainsMono Nerd Font"
FontSize="14"

RoundCorners="16"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, MMMM d"

HeaderText="Welcome back, William"

#################### Background ####################

BackgroundPlaceholder=""
Background="/usr/share/pixmaps/greeter-bg.jpg"
BackgroundSpeed="1.0"
DimBackground="0.2"
CropBackground="true"

#################### Colors ####################

HeaderTextColor="#00f5ff"
DateTextColor="#d0d0d8"
TimeTextColor="#00f5ff"

FormBackgroundColor="#0d0d1a"
BackgroundColor="#0d0d1a"
DimBackgroundColor="#000000"

LoginFieldBackgroundColor="#111122"
PasswordFieldBackgroundColor="#111122"
LoginFieldTextColor="#edf1f7"
PasswordFieldTextColor="#edf1f7"
UserIconColor="#00f5ff"
PasswordIconColor="#00f5ff"

PlaceholderTextColor="#8892a0"
WarningColor="#ff3c6f"

LoginButtonTextColor="#0d0d1a"
LoginButtonBackgroundColor="#00f5ff"
SystemButtonsIconsColor="#00f5ff"
SessionButtonTextColor="#00f5ff"
VirtualKeyboardButtonTextColor="#00f5ff"

DropdownTextColor="#0d0d1a"
DropdownSelectedBackgroundColor="#00f5ff"
DropdownBackgroundColor="#1a1a2e"

HighlightTextColor="#0d0d1a"
HighlightBackgroundColor="#00f5ff"
HighlightBorderColor="transparent"

HoverUserIconColor="#ffffff"
HoverPasswordIconColor="#ffffff"
HoverSystemButtonsIconsColor="#ffffff"
HoverSessionButtonTextColor="#ffffff"
HoverVirtualKeyboardButtonTextColor="#ffffff"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="12"
Blur="2.0"

HaveFormBackground="true"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"
